feat(cfg): env secret/string support
getoutreach/gobox pull request #592
Opened 2024-10-11 23:08 UTC by AndrewWinterman

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!

## What this PR does / why we need it

## Jira ID

[XX-XX]

## Notes for your reviewers

2024-10-11 23:58 UTC, malept requested changes
This seems mostly fine but the tests should be using `gotest.tools/v3/assert`.

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +	}
suggestion: I would use `gotest.tools/v3/assert` here.
```suggestion
	assert.NilError(t, err, "failed to set environment variable")
```

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +		}
```suggestion
		assert.Equal(t, v, value)
```

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +	}
```suggestion
	assert.NilError(t, err, "failed to set environment variable")
```

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +		}
```suggestion
		t.ErrorContains(t, err, notsetKey)
		t.ErrorContains(t, err, "environment variable not set")
```

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +	}
```suggestion
	assert.NilError(t, err)
```

2024-10-11 23:58 UTC, malept commented on pkg/cfg/env_test.go
> +	}
```suggestion
	assert.Equal(t, string(v), value)
```

2024-10-14 16:38 UTC, malept approved these changes
Looks fine once the copyright date is changed.

2024-10-14 16:38 UTC, malept commented on pkg/cfg/env.go
> +// Copyright 2022 Outreach Corporation. All Rights Reserved.
Nit:
```suggestion
// Copyright 2024 Outreach Corporation. All Rights Reserved.
```

2024-10-14 17:16 UTC, daniel-dostal84 approved these changes

2024-10-14 17:16 UTC, merged