feat: request route
getoutreach/gobox pull request #602
Opened 2024-11-12 09:06 UTC by pavelsmejkal

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!

## What this PR does / why we need it

## Jira ID

[XX-XX]

## Notes for your reviewers

2024-11-12 18:55 UTC, malept requested changes
Conceptually this seems fine, but it needs some polish.

2024-11-12 18:55 UTC, malept commented on pkg/events/events.go
> +	// Route is path without extrapolated path variables
Nit:
```suggestion
	// Route is the URL path without interpolating the path variables.
```

2024-11-12 18:55 UTC, malept commented on pkg/events/events.go
> +// requestRouteCtxKey represents the context key for the request route
Nit:
```suggestion
// requestRouteCtxKey represents the context key for the request route.
```

2024-11-12 18:55 UTC, malept commented on pkg/events/events.go
> +// WithRequestTime adds a given time to a context as a request time
issue: this was not changed from the copy/paste.

2024-11-12 18:55 UTC, malept commented on pkg/events/events.go
> +// RequestRoute returns a request route present in the context or empty string
Nit:
```suggestion
// RequestRoute retrieves the request route present in the context, if available.
```

2024-11-12 18:55 UTC, malept commented on pkg/events/marshalers.go
> +    }
issue: the indentation is inconsistent from the context.

2024-11-13 17:38 UTC, malept approved these changes

2024-11-14 15:10 UTC, john-dostal approved these changes

2024-11-14 15:46 UTC, milankonir approved these changes

2024-11-14 16:18 UTC, merged

2025-01-09 01:05 UTC, malept commented on pkg/events/marshalers.go
> +	}
issue: as it turns out, this change is in an autogenerated file, so this change gets reverted every time `make gogenerate` is run, which also happens every time a re-stencil happens.